//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySnapApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScaleComPort {
            get {
                return ((string)(this["ScaleComPort"]));
            }
            set {
                this["ScaleComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("733")]
        public string ExportSiteId {
            get {
                return ((string)(this["ExportSiteId"]));
            }
            set {
                this["ExportSiteId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in")]
        public string ExportDimUnit {
            get {
                return ((string)(this["ExportDimUnit"]));
            }
            set {
                this["ExportDimUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lb")]
        public string ExportWgtUnit {
            get {
                return ((string)(this["ExportWgtUnit"]));
            }
            set {
                this["ExportWgtUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in")]
        public string ExportVolUnit {
            get {
                return ((string)(this["ExportVolUnit"]));
            }
            set {
                this["ExportVolUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("166")]
        public string ExportFactor {
            get {
                return ((string)(this["ExportFactor"]));
            }
            set {
                this["ExportFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string ExportOptInfo2 {
            get {
                return ((string)(this["ExportOptInfo2"]));
            }
            set {
                this["ExportOptInfo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string ExportOptInfo3 {
            get {
                return ((string)(this["ExportOptInfo3"]));
            }
            set {
                this["ExportOptInfo3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPEG_Large")]
        public string CameraImageQuality {
            get {
                return ((string)(this["CameraImageQuality"]));
            }
            set {
                this["CameraImageQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPEG")]
        public string CameraImageFormat {
            get {
                return ((string)(this["CameraImageFormat"]));
            }
            set {
                this["CameraImageFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPartNumber {
            get {
                return ((string)(this["LastPartNumber"]));
            }
            set {
                this["LastPartNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("733")]
        public string DimsSiteId {
            get {
                return ((string)(this["DimsSiteId"]));
            }
            set {
                this["DimsSiteId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("166")]
        public string DimsFactor {
            get {
                return ((string)(this["DimsFactor"]));
            }
            set {
                this["DimsFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in")]
        public string DimsDimUnit {
            get {
                return ((string)(this["DimsDimUnit"]));
            }
            set {
                this["DimsDimUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lb")]
        public string DimsWgtUnit {
            get {
                return ((string)(this["DimsWgtUnit"]));
            }
            set {
                this["DimsWgtUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in")]
        public string DimsVolUnit {
            get {
                return ((string)(this["DimsVolUnit"]));
            }
            set {
                this["DimsVolUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string DimsOptInfo2 {
            get {
                return ((string)(this["DimsOptInfo2"]));
            }
            set {
                this["DimsOptInfo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string DimsOptInfo3 {
            get {
                return ((string)(this["DimsOptInfo3"]));
            }
            set {
                this["DimsOptInfo3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DimsOptInfo8 {
            get {
                return ((string)(this["DimsOptInfo8"]));
            }
            set {
                this["DimsOptInfo8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string DimsUpdated {
            get {
                return ((string)(this["DimsUpdated"]));
            }
            set {
                this["DimsUpdated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DimsEnableOverride {
            get {
                return ((bool)(this["DimsEnableOverride"]));
            }
            set {
                this["DimsEnableOverride"] = value;
            }
        }
    }
}
